plugins {
    id 'com.android.application' version '8.2.2'
    id 'org.jetbrains.kotlin.android' version '1.9.22'
}

android {
    namespace 'com.downls10'
    compileSdk 34

    defaultConfig {
        applicationId 'com.downls10'
        minSdk 24
        targetSdk 34
        versionCode 57
        versionName '5.7'
    }

    signingConfigs {
        debug {
            storeFile file("signing/downls10-stable.jks")
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
            signingConfig signingConfigs.debug
        }
        release {
            debuggable false
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.debug
        }
    }

    sourceSets {
        main {
            manifest.srcFile 'src/main/AndroidManifest.xml'
            java.srcDirs = ['src/main/java', 'src/main/kotlin']
            res.srcDirs = ['src/main/res']
            assets.srcDirs = ['src/main/assets']
        }
        debug {
            java.srcDirs = ['src/debug/java', 'src/debug/kotlin']
            res.srcDirs = ['src/debug/res']
            assets.srcDirs = ['src/debug/assets']
        }
        release {
            java.srcDirs = ['src/release/java', 'src/release/kotlin']
            res.srcDirs = ['src/release/res']
            assets.srcDirs = ['src/release/assets']
        }
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
}
